autoLinkIssue: true
autoCloseIssue: true
defaultBranch: 'dev'
openDraftPR: false
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
conventionalPrTitles: true
